version: 0.2

phases:
pre_build:
commands:
- echo "Logging in to Amazon ECR..."
- AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
- ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app
- aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com

build:
commands:
- echo "Building Docker image..."
- docker build -t brain-task-app:latest .
- docker tag brain-task-app:latest $ECR_URI:latest
- echo "Pushing Docker image to Amazon ECR..."
- docker push $ECR_URI:latest

post_build:
commands:
- echo "Updating EKS kubeconfig..."
- aws eks update-kubeconfig --region ap-south-1 --name brain-task-cluster

  - echo "Checking EKS cluster..."
  - kubectl get nodes

  - echo "Applying Kubernetes Deployment..."
  - kubectl apply -f deployment.yaml

  - echo "Applying Kubernetes Service..."
  - kubectl apply -f service.yaml

  - echo "Applying Kubernetes Ingress..."
  - kubectl apply -f ingress.yaml

  - echo "Updating Deployment image..."
  - kubectl set image deployment/brain-task-app brain-task-app=$ECR_URI:latest

  - echo "Waiting for deployment rollout..."
  - kubectl rollout status deployment/brain-task-app --timeout=180s

  - echo "Checking Pods..."
  - kubectl get pods

  - echo "Checking Services..."
  - kubectl get svc

  - echo "Checking Ingress..."
  - kubectl get ingress

  - echo "Build and deployment completed successfully."
